name: buzzerbeater
description: BuzzerBeater - 让篮球更有趣，让球迷更懂球，让打球更容易
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.0
  
  # 网络请求
  dio: ^5.4.0
  
  # 本地存储
  shared_preferences: ^2.2.0
  
  # 图片选择
  image_picker: ^1.0.4
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

